# Имя устройства (попробуй кириллицу, если упадет - смени на RhinoPad)
CONFIG_ZMK_KEYBOARD_NAME="RhinoPAD_Blya"

# Глубокий сон (Deep Sleep) через 15 минут
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=300000

# Отключаем автоматический запуск поиска при включении, если нет связи
# Это заставит его ждать твоего комбо Esc+Enter
CONFIG_ZMK_BLE_PASSIVE_SCANNING=n

# Ограничиваем время видимости в поиске (60 секунд)
# Если за минуту не подключился — радио выключается
CONFIG_BT_LIM_ADV_TIMEOUT=60

# Мощность сигнала (0 - стандарт, бережет батарею 120mAh)
CONFIG_BT_CTLR_TX_PWR_0=y

# Передача заряда батареи
CONFIG_ZMK_BATTERY_REPORTING=y
