# Имя устройства
CONFIG_ZMK_KEYBOARD_NAME="RhinoPad_Blyad"

# Энергосбережение
CONFIG_ZMK_SLEEP=y
# 15 минут до глубокого сна
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# Передача уровня заряда
CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_BATTERY_REPORT_INTERVAL=60

# Оптимизация Bluetooth
# Ограничение времени поиска нового устройства (60 секунд)
CONFIG_BT_LIM_ADV_TIMEOUT=60
