# --- ИМЯ УСТРОЙСТВА ---
CONFIG_ZMK_KEYBOARD_NAME="РайноБлять"

# --- ЭНЕРГОПОТРЕБЛЕНИЕ ---
# Разрешаем глубокий сон (Deep Sleep)
CONFIG_ZMK_SLEEP=y
# Переход в режим ожидания (Idle) через 30 секунд (отключает BT рекламу)
CONFIG_ZMK_IDLE_TIMEOUT=30000
# Полное выключение (Deep Sleep) через 15 минут бездействия (900 000 мс)
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# --- ОПТИМИЗАЦИЯ BLUETOOTH ---
# Уменьшаем мощность передатчика. Для макропада на столе 0 или -4 достаточно.
# Это сильно экономит заряд по сравнению со стандартом +4.
CONFIG_BT_CTLR_TX_PWR_0=y

# --- ИНДИКАЦИЯ ЗАРЯДА ---
# Передача уровня заряда батареи на компьютер/телефон
CONFIG_ZMK_BATTERY_REPORTING=y
# Интервал обновления заряда (раз в 60 секунд)
CONFIG_ZMK_BATTERY_REPORT_INTERVAL=60

# --- СТАБИЛЬНОСТЬ ---
# Увеличиваем надежность комбо-нажатий (для твоего сброса Bluetooth)
CONFIG_ZMK_COMBO_MAX_COMBOS_PER_KEY=1
